name: CI Global - Services indépendants

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build & test auth-service
        run: |
          cd auth-service
          mvn clean install

      - name: Build & test commande-service
        run: |
          cd commande-service
          mvn clean install

      - name: Build & test livre-service
        run: |
          cd livre-service
          mvn clean install

      - name: Build & test notification-service
        run: |
          cd notification-service
          mvn clean install

      - name: Build & test user-service
        run: |
          cd user-service
          mvn clean install
